force-app/main/default/objects/K_Contact__c/K_Contact__c.object-meta.xml
<CustomObject>
    <description>This Object includes existing Kanlet&apos;s Contacts.</description>
    <label>Inscope Contact</label>
    <nameField>
        <displayFormat>KC_{00000}</displayFormat>
        <label>KC_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inscope Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/K_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indicates Contact Id fetched from standard contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>K Contacts</relationshipLabel>
    <relationshipName>K_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/K_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>First name of the contact fetched from standard contact.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Contact__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <inlineHelpText>Designation of the contact fetched from standard contact.</inlineHelpText>
    <label>Job Title</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Last name of the contact fetched from standard contact.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/K_Processed_Contact__c.object-meta.xml
<CustomObject>
    <description>This object includes the processed contact records(i.e. updated contacts).</description>
    <label>Processed Contact</label>
    <nameField>
        <displayFormat>KPC-{0000}</displayFormat>
        <label>KPC_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processed Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/K_Processed_Contact__c/fields/Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Action_Taken__c</fullName>
    <label>Action Taken</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Action Taken</fullName>
                <default>true</default>
                <label>No Action Taken</label>
            </value>
            <value>
                <fullName>Create Contact</fullName>
            </value>
            <value>
                <fullName>Create Lead</fullName>
            </value>
            <value>
                <fullName>Promoted</fullName>
            </value>
            <value>
                <fullName>Skip</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Merge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <inlineHelpText>Previous company of the contact received from Kanlet.</inlineHelpText>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <inlineHelpText>Indicates the current status of the contact.</inlineHelpText>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joined</fullName>
            </value>
            <value>
                <fullName>Promoted</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>First Name of the contact.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <inlineHelpText>Previous Designation of the contact received from Kanlet.</inlineHelpText>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/K_Contact__c.field-meta.xml
<CustomField>
    <fullName>K_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>K Contact</label>
    <referenceTo>K_Contact__c</referenceTo>
    <relationshipLabel>K Processed Contacts</relationshipLabel>
    <relationshipName>K_Processed_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Last Name of the contact.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/New_Company__c.field-meta.xml
<CustomField>
    <fullName>New_Company__c</fullName>
    <inlineHelpText>New company of the contact received from Kanlet.</inlineHelpText>
    <label>New Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/K_Processed_Contact__c/fields/New_Designation__c.field-meta.xml
<CustomField>
    <fullName>New_Designation__c</fullName>
    <inlineHelpText>New Designation of the contact received from Kanlet.</inlineHelpText>
    <label>New Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactJourneyController.cls
public with sharing class ContactJourneyController {		
    
    @AuraEnabled
    public static K_Processed_Contact__c getCareerEventsByContactId(string contactId) {
       // Contact con= [SELECT Id,Name,FirstName,LastName,Job_Title__c,AccountId FROM Contact WHERE Id=:contactId];
     //   K_Contact__c kContacts = [SELECT Id FROM K_Contact__c WHERE Contact__c = :contactId LIMIT 1];
          List<K_Processed_Contact__c> careerEvents =new List<K_Processed_Contact__c>();
      //  system.debug('kContacts --> '+kContacts);
           // String kContactId = kContacts.Id;
           careerEvents = [SELECT Id, Company__c,First_Name__c,ContactId__c,Last_Name__C, Job_Title__c, Contact_Status__c, New_Company__c, New_Designation__c ,
                           K_Contact__c,K_Contact__r.Contact__c,Action_Taken__c FROM K_Processed_Contact__c 
                           WHERE ContactId__c=:contactId OR K_Contact__r.Contact__c=:contactId limit 1];
        system.debug('ContactId__c--> '+careerEvents[0].ContactId__c);
        system.debug('contactId--> '+contactId);
        system.debug('K_Contact__r.Contact__c--> '+careerEvents[0].K_Contact__r.Contact__c);
      //  system.debug('ContactId__c--> '+ContactId__c);
            system.debug('careerEvents--> '+careerEvents);
       
        
         return careerEvents[0];
    }
}